"""PostgreSQL syntax validation tests.

The validator is an ALLOWLIST defined by PostgreSQL itself (pglast wraps
libpg_query, the server's own C parser), unlike the linter which is a BLOCKLIST
of anticipated defects. Only the validator catches unknown unknowns.
"""

import pytest

from core import orchestrator, validator
from core.models import Severity


def test_pglast_is_available():
    """If this fails the packaged build silently degrades to NOT CHECKED."""
    assert validator.AVAILABLE, "pglast must be installed"


# --------------------------------------------------------------------------
# Accepts valid PostgreSQL
# --------------------------------------------------------------------------

@pytest.mark.parametrize("sql", [
    "SELECT a FROM t LIMIT 1",
    "SELECT * FROM a INNER JOIN LATERAL (SELECT 1) x ON TRUE",
    "MERGE INTO t USING s ON t.a=s.a WHEN MATCHED THEN UPDATE SET b=s.b",
    "CREATE TABLE t (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)",
    "DO $$ BEGIN PERFORM 1; END $$;",
    "SELECT 1; SELECT 2;",
    'CREATE TEMPORARY TABLE "UserTarget" ("ID" INT)',
])
def test_accepts_valid_postgresql(sql):
    assert validator.validate(sql).valid, sql


@pytest.mark.parametrize("sql", [
    "SELECT * FROM t WHERE a = @Id",
    "SELECT * FROM t LIMIT @PageSize",
    "INSERT INTO t (a, b) VALUES (@a, @b)",
    "UPDATE t SET a = @a WHERE id = @id",
])
def test_accepts_dapper_parameters(sql):
    """Npgsql substitutes @name client-side; the grammar tolerates them."""
    assert validator.validate(sql).valid, sql


# --------------------------------------------------------------------------
# Rejects what the linter might miss
# --------------------------------------------------------------------------

@pytest.mark.parametrize("sql,hint", [
    ("SELECT * FROM t WHERE a = $TableName", "sqlglot's invalid $var rendering"),
    ("CREATE TABLE t (a VARCHAR(MAX))", "VARCHAR(MAX) survived"),
    ("DECLARE $x VARCHAR(50)", "T-SQL DECLARE survived"),
    ("SELECT TOP 10 * FROM t", "TOP survived"),
    ("SELECT * FROM t WITH (NOLOCK)", "NOLOCK survived"),
    ("SELEKT * FRM", "malformed input"),
    ("SELECT * FROM t WHERE )", "unbalanced syntax"),
])
def test_rejects_invalid_postgresql(sql, hint):
    result = validator.validate(sql)
    assert not result.valid, hint
    assert result.errors


def test_error_reports_line_and_column():
    result = validator.validate("SELECT a\nFROM t\nWHERE TOP 5")
    assert not result.valid
    assert "line" in result.errors[0] and "column" in result.errors[0]


def test_empty_sql_is_invalid():
    assert not validator.validate("   ").valid


def test_validate_never_raises():
    for junk in ["", "\x00", "'", "((((", "$$"]:
        assert isinstance(validator.validate(junk), validator.Validation)



# --------------------------------------------------------------------------
# Honest about its own limits
# --------------------------------------------------------------------------

@pytest.mark.parametrize("sql", [
    "SELECT CAST(x AS BIT) FROM t",       # BIT is a real PG type, wrong one
    "SELECT a + ' - ' + b FROM t",        # fails at RUNTIME: text + text
    "SELECT ISNULL(a, 0) FROM t",         # fails at RUNTIME: no such function
])
def test_valid_syntax_wrong_semantics_still_passes(sql):
    """DOCUMENTED LIMIT: these parse cleanly and need PREPARE or execution to
    catch. The linter covers them (L003/L001/L008) -- that is why both exist."""
    assert validator.validate(sql).valid


def test_verdict_strings():
    assert validator.validate("SELECT 1").verdict == "VALID"
    assert validator.validate("SELEKT").verdict == "INVALID"
    assert validator.Validation(checked=False).verdict == "NOT CHECKED"


# --------------------------------------------------------------------------
# Integration: every engine result is validated
# --------------------------------------------------------------------------

def test_orchestrator_validates_engine_output():
    result = orchestrator.convert("SELECT TOP 1 * FROM t")
    assert result.validation is not None
    assert result.validation.valid


def test_invalid_output_is_reported_as_an_error():
    """sqlglot leaves a DECLAREd local as $x, which PostgreSQL cannot parse."""
    result = orchestrator.convert("DECLARE @x NVARCHAR(MAX); SELECT @x;")
    assert result.validation is not None
    assert not result.validation.valid
    assert any(w.code == "PG-SYNTAX" and w.severity is Severity.ERROR
               for w in result.warnings)
    assert not result.is_usable


def test_valid_output_adds_no_syntax_error():
    result = orchestrator.convert("SELECT TOP 1 a FROM t")
    assert not any(w.code == "PG-SYNTAX" and w.severity is Severity.ERROR
                   for w in result.warnings)


def test_insights_lead_with_the_syntax_verdict():
    from core import insights
    original = "SELECT TOP 1 a FROM t"
    result = orchestrator.convert(original)
    data = insights.analyze(original, result.sql, result.warnings,
                            result.validation)
    assert data.syntax == "VALID"
    assert "PostgreSQL syntax: VALID" in insights.render_text(data)
